# Generated by Django 3.1.14 on 2022-04-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_friend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
