# Generated by Django 3.1.14 on 2022-04-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_id',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='signature_id',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
