# Generated by Django 3.1.14 on 2022-04-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20220427_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='razor_subscription_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='signature_id',
        ),
    ]
